// website/app/components/Links.tsx
'use client';

export default function Links() {
  const links = [
    { label: 'GitHub', url: 'https://github.com/thomasboom', icon: 'GH' },
    {
      label: 'Mastodon',
      url: 'https://mastodon.social/@thomasnow',
      icon: 'MA',
    },
    {
      label: 'Bluesky',
      url: 'https://bsky.app/profile/thomasnowprod.bsky.social',
      icon: 'BS',
    },
    { label: 'Email', url: 'mailto:thomasnowprod@proton.me', icon: '@' },
  ];

  return (
    <div className="links">
      {links.map((link) => (
        <a
          key={link.url}
          href={link.url}
          target="_blank"
          rel="noopener noreferrer"
          className="links-link"
        >
          <span className="links-icon">{link.icon}</span>
          <span>{link.label}</span>
        </a>
      ))}
    </div>
  );
}

// website/src/lib/components/Links.svelte
<div class="links">
  <a
    href="https://github.com/thomasboom"
    target="_blank"
    rel="noopener noreferrer"
    class="links-link"
  >
    <span class="links-icon">GH</span>
    <span>GitHub</span>
  </a>
  <a
    href="https://mastodon.social/@thomasnow"
    target="_blank"
    rel="noopener noreferrer"
    class="links-link"
  >
    <span class="links-icon">MA</span>
    <span>Mastodon</span>
  </a>
  <a
    href="https://bsky.app/profile/thomasnowprod.bsky.social"
    target="_blank"
    rel="noopener noreferrer"
    class="links-link"
  >
    <span class="links-icon">BS</span>
    <span>Bluesky</span>
  </a>
  <a
    href="mailto:thomasnowprod@proton.me"
    target="_blank"
    rel="noopener noreferrer"
    class="links-link"
  >
    <span class="links-icon">@</span>
    <span>Email</span>
  </a>
</div>
