// website/app/components/Work.tsx
export default function Work() {
  return (
    <section className="section" id="work">
      <div className="section-header">
        <h2 className="section-title">01 — SELECTED WORK</h2>
        <span className="section-line"></span>
      </div>

      <article className="work-item">
        <h3>
          <a
            href="https://codeberg.org/thomasboom/YAM-Launcher"
            target="_blank"
            rel="noopener noreferrer"
          >
            YAM Launcher
          </a>
        </h3>
        <p>A fast, open and customizable launcher for Android</p>
        <div className="tech">
          <span>Kotlin</span>
          <span>Google Play Store</span>
          <span>F-Droid</span>
          <span>Izzyondroid</span>
        </div>
      </article>

      <article className="work-item">
        <h3>
          <a href="https://ipcar.dev" target="_blank" rel="noopener noreferrer">
            IP-Car
          </a>
        </h3>
        <p>
          A remote-controlled robot that gives children with disabilities a real
          presence in the classroom, from home
        </p>
        <div className="tech">
          <span>Svelte</span>
          <span>Electron</span>
        </div>
      </article>

      <article className="work-item">
        <h3>
          <a
            href="https://thomasboom.codeberg.page/SupGIT/"
            target="_blank"
            rel="noopener noreferrer"
          >
            SupGit
          </a>
        </h3>
        <p>
          A simplified Git CLI for beginners who don&apos;t want to leave the
          terminal
        </p>
        <div className="tech">
          <span>Rust</span>
          <span>Git</span>
          <span>CLI</span>
        </div>
      </article>

      <article className="work-item">
        <h3>
          <a
            href="https://thomasboom.codeberg.page/AIRun/"
            target="_blank"
            rel="noopener noreferrer"
          >
            AIRun
          </a>
        </h3>
        <p>
          Forgot that you have dozens of AI CLIs installed? Find the one you
          need before executing your prompt
        </p>
        <div className="tech">
          <span>Rust</span>
          <span>CLI</span>
        </div>
      </article>

      <article className="work-item">
        <h3>
          <a
            href="https://bijbelquiz.app"
            target="_blank"
            rel="noopener noreferrer"
          >
            BijbelQuiz
          </a>
        </h3>
        <p>Test your Bible knowledge with engaging quizzes.</p>
        <div className="tech">
          <span>Flutter</span>
          <span>Dart</span>
          <span>Supabase</span>
          <span>Gemini API</span>
        </div>
      </article>

      <details className="work-collapsible">
        <summary className="work-summary">Contributed to</summary>
        <div className="work-collapsible-content">
          <article className="work-item">
            <h3>
              <a
                href="https://zed.dev"
                target="_blank"
                rel="noopener noreferrer"
              >
                Zed
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://signal.org"
                target="_blank"
                rel="noopener noreferrer"
              >
                Signal Android
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://antennapod.org/"
                target="_blank"
                rel="noopener noreferrer"
              >
                AntennaPod
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://killedbygoogle.com/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Killed by Google
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://tools.rmv.fyi/"
                target="_blank"
                rel="noopener noreferrer"
              >
                DelphiTools
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://n20.me/"
                target="_blank"
                rel="noopener noreferrer"
              >
                N20
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/Githubguy132010/devvy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Devvy
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://kilo.ai"
                target="_blank"
                rel="noopener noreferrer"
              >
                KiloCode
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://questphone.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                QuestPhone
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/SchweGELBin/OpenBible2"
                target="_blank"
                rel="noopener noreferrer"
              >
                OpenBible2
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/TopMyster/Ripple"
                target="_blank"
                rel="noopener noreferrer"
              >
                Ripple
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/Trease-Focus/trease-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Trease App
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/cgueret/Scriptorium"
                target="_blank"
                rel="noopener noreferrer"
              >
                Scriptorium
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/dhruv0206/dev-proof-portfolio-open-source-search"
                target="_blank"
                rel="noopener noreferrer"
              >
                Dev Proof Portfolio Open Source Search
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/emersion/hydroxide"
                target="_blank"
                rel="noopener noreferrer"
              >
                Hydroxide
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/ervan0707/bitchat-web"
                target="_blank"
                rel="noopener noreferrer"
              >
                Bitchat Web
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/flathub/flathub"
                target="_blank"
                rel="noopener noreferrer"
              >
                Flathub
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/is-a-dev/register"
                target="_blank"
                rel="noopener noreferrer"
              >
                is-a-dev Register
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/is-a-software/is-a-software"
                target="_blank"
                rel="noopener noreferrer"
              >
                is-a-software
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/is-an-ai-dev/register"
                target="_blank"
                rel="noopener noreferrer"
              >
                is-an-ai-dev Register
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/kem-a/AppManager"
                target="_blank"
                rel="noopener noreferrer"
              >
                AppManager
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/pop-os/popsicle"
                target="_blank"
                rel="noopener noreferrer"
              >
                Popsicle
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/sk88studiosinc-maker/Soulsound"
                target="_blank"
                rel="noopener noreferrer"
              >
                Soulsound
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/thepushkarp/wasclaudedowntoday"
                target="_blank"
                rel="noopener noreferrer"
              >
                Was Claude Down Today
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/thomasboom/BreathSpace"
                target="_blank"
                rel="noopener noreferrer"
              >
                BreathSpace
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/urikdev/Urik"
                target="_blank"
                rel="noopener noreferrer"
              >
                Urik
              </a>
            </h3>
          </article>
          <article className="work-item">
            <h3>
              <a
                href="https://github.com/yjeanrenaud/yj_nearbyglasses"
                target="_blank"
                rel="noopener noreferrer"
              >
                Nearby Glasses
              </a>
            </h3>
          </article>
        </div>
      </details>
    </section>
  );
}

// website/src/lib/components/Work.svelte
<script lang="ts">
  import { t } from '$lib/language';
</script>

<section class="section" id="work">
  <div class="section-header">
    <h2 class="section-title">{$t.sections.work}</h2>
    <span class="section-line"></span>
  </div>

  <article class="work-item">
    <h3>
      <a href="https://codeberg.org/thomasboom/YAM-Launcher" target="_blank" rel="noopener noreferrer">
        YAM Launcher
      </a>
    </h3>
    <p>{$t.work.yam}</p>
    <div class="tech"><span>Kotlin</span><span>Google Play Store</span><span>F-Droid</span><span>Izzyondroid</span></div>
  </article>

  <article class="work-item">
    <h3><a href="https://ipcar.dev" target="_blank" rel="noopener noreferrer">IP-Car</a></h3>
    <p>{$t.work.ipcar}</p>
    <div class="tech"><span>Svelte</span><span>Electron</span></div>
  </article>

  <article class="work-item">
    <h3>
      <a href="https://thomasboom.codeberg.page/SupGIT/" target="_blank" rel="noopener noreferrer">SupGit</a>
    </h3>
    <p>{$t.work.supgit}</p>
    <div class="tech"><span>Rust</span><span>Git</span><span>CLI</span></div>
  </article>

  <article class="work-item">
    <h3><a href="https://thomasboom.codeberg.page/AIRun/" target="_blank" rel="noopener noreferrer">AIRun</a></h3>
    <p>{$t.work.airun}</p>
    <div class="tech"><span>Rust</span><span>CLI</span></div>
  </article>

  <article class="work-item">
    <h3><a href="https://bijbelquiz.app" target="_blank" rel="noopener noreferrer">BijbelQuiz</a></h3>
    <p>{$t.work.bijbelquiz}</p>
    <div class="tech"><span>Flutter</span><span>Dart</span><span>Supabase</span><span>Gemini API</span></div>
  </article>

  <details class="work-collapsible">
    <summary class="work-summary">{$t.work.contributedTo}</summary>
    <div class="work-collapsible-content">
      <article class="work-item"><h3><a href="https://zed.dev" target="_blank" rel="noopener noreferrer">Zed</a></h3></article>
      <article class="work-item"><h3><a href="https://signal.org" target="_blank" rel="noopener noreferrer">Signal Android</a></h3></article>
      <article class="work-item"><h3><a href="https://antennapod.org/" target="_blank" rel="noopener noreferrer">AntennaPod</a></h3></article>
      <article class="work-item"><h3><a href="https://killedbygoogle.com/" target="_blank" rel="noopener noreferrer">Killed by Google</a></h3></article>
      <article class="work-item"><h3><a href="https://tools.rmv.fyi/" target="_blank" rel="noopener noreferrer">DelphiTools</a></h3></article>
      <article class="work-item"><h3><a href="https://n20.me/" target="_blank" rel="noopener noreferrer">N20</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/Githubguy132010/devvy" target="_blank" rel="noopener noreferrer">Devvy</a></h3></article>
      <article class="work-item"><h3><a href="https://kilo.ai" target="_blank" rel="noopener noreferrer">KiloCode</a></h3></article>
      <article class="work-item"><h3><a href="https://questphone.app/" target="_blank" rel="noopener noreferrer">QuestPhone</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/SchweGELBin/OpenBible2" target="_blank" rel="noopener noreferrer">OpenBible2</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/TopMyster/Ripple" target="_blank" rel="noopener noreferrer">Ripple</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/Trease-Focus/trease-app" target="_blank" rel="noopener noreferrer">Trease App</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/cgueret/Scriptorium" target="_blank" rel="noopener noreferrer">Scriptorium</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/dhruv0206/dev-proof-portfolio-open-source-search" target="_blank" rel="noopener noreferrer">Dev Proof Portfolio Open Source Search</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/emersion/hydroxide" target="_blank" rel="noopener noreferrer">Hydroxide</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/ervan0707/bitchat-web" target="_blank" rel="noopener noreferrer">Bitchat Web</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/flathub/flathub" target="_blank" rel="noopener noreferrer">Flathub</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/is-a-dev/register" target="_blank" rel="noopener noreferrer">is-a-dev Register</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/is-a-software/is-a-software" target="_blank" rel="noopener noreferrer">is-a-software</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/is-an-ai-dev/register" target="_blank" rel="noopener noreferrer">is-an-ai-dev Register</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/kem-a/AppManager" target="_blank" rel="noopener noreferrer">AppManager</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/pop-os/popsicle" target="_blank" rel="noopener noreferrer">Popsicle</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/sk88studiosinc-maker/Soulsound" target="_blank" rel="noopener noreferrer">Soulsound</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/thepushkarp/wasclaudedowntoday" target="_blank" rel="noopener noreferrer">Was Claude Down Today</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/thomasboom/BreathSpace" target="_blank" rel="noopener noreferrer">BreathSpace</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/urikdev/Urik" target="_blank" rel="noopener noreferrer">Urik</a></h3></article>
      <article class="work-item"><h3><a href="https://github.com/yjeanrenaud/yj_nearbyglasses" target="_blank" rel="noopener noreferrer">Nearby Glasses</a></h3></article>
    </div>
  </details>
</section>
