// website/src/lib/components/Navigation.svelte
<script lang="ts">
  import { t } from '$lib/language';

  const scrollTo = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };
</script>

<nav class="nav" aria-label="Main navigation">
  <a href="/blog"><span class="nav-number">00</span> {$t.nav.blog}</a>
  <a
    href="#about"
    onclick={(e) => {
      e.preventDefault();
      scrollTo('about');
    }}
  >
    <span class="nav-number">01</span> {$t.nav.about}
  </a>
  <a
    href="#work"
    onclick={(e) => {
      e.preventDefault();
      scrollTo('work');
    }}
  >
    <span class="nav-number">02</span> {$t.nav.work}
  </a>
  <a
    href="#skills"
    onclick={(e) => {
      e.preventDefault();
      scrollTo('skills');
    }}
  >
    <span class="nav-number">03</span> {$t.nav.skills}
  </a>
  <a
    href="#contact"
    onclick={(e) => {
      e.preventDefault();
      scrollTo('contact');
    }}
  >
    <span class="nav-number">04</span> {$t.nav.contact}
  </a>
</nav>

// website/app/components/Navigation.tsx
'use client';

import Link from 'next/link';

export default function Navigation() {
  const scrollTo = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <nav className="nav">
      <a href="#work" onClick={(e) => { e.preventDefault(); scrollTo('work'); }}>
        <span className="nav-number">01</span> Work
      </a>
      <a href="#skills" onClick={(e) => { e.preventDefault(); scrollTo('skills'); }}>
        <span className="nav-number">02</span> Skills
      </a>
      <a href="#about" onClick={(e) => { e.preventDefault(); scrollTo('about'); }}>
        <span className="nav-number">03</span> About
      </a>
      <Link href="/blog">
        <span className="nav-number">04</span> Blog
      </Link>
      <a href="#contact" onClick={(e) => { e.preventDefault(); scrollTo('contact'); }}>
        <span className="nav-number">05</span> Contact
      </a>
    </nav>
  );
}
