// website/src/routes/links/+page.svelte
<script lang="ts">
  import { t } from '$lib/language';
  import Links from '$lib/components/Links.svelte';
</script>

<div class="links-container">
  <div class="links-header">
    <h1 class="name">
      <span>Thomas</span>
      <span class="accent">Boom</span>
    </h1>
    <p class="meta">{$t.hero.building}</p>
  </div>
  <Links />
  <a href="/" class="back-link">← {$t.links.backHome}</a>
</div>

// website/app/links/page.tsx
'use client';

import Link from 'next/link';
import Links from '../components/Links';
import { LanguageProvider, useLanguage } from '../components/LanguageProvider';

function LinksPageContent() {
  const { t } = useLanguage();

  return (
    <div className="links-container">
      <div className="links-header">
        <h1 className="name">
          <span>Thomas</span>
          <span className="accent">Boom</span>
        </h1>
        <p className="meta">{t.hero.building}</p>
      </div>
      <Links />
      <Link href="/" className="back-link">
        ← {t.links.backHome}
      </Link>
    </div>
  );
}

export default function LinksPage() {
  return (
    <LanguageProvider>
      <LinksPageContent />
    </LanguageProvider>
  );
}
